name: Publish Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js and authenticate to GitHub Packages
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@dev-axay18'
        always-auth: true

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
